### ISSUE TITLE
Can i replace the mindustry client download

### ISSUE THREAD

**Issue by JasonP01** [xpdustry/toxopid#4]
So the default vanilla client has its fair share of "issues", so to speed up testing aspects, im willing to create a version of the game that imports some foos aspects, such as multithreaded server list loading so its less laggy, and other optimizations that would not cause issues with testing aspects using toxopid's runMindustryClient task. 

Obviously the repo will be open source, and only contain the optimizations with the base vanilla game

Completely understandable if you decline and choose to keep it completely vanilla

**Comment by phinner** [comment]
If you wish to use foo's client for testing, modify the `downloadMindustryClient` task to download it instead of the vanilla client.
Add this at the bottom of the build script.
```kt
tasks.downloadMindustryClient {
    user.set("mindustry-antigrief")
    repo.set("mindustry-client-v7-builds")
    name.set("desktop.jar")
    version.set("1673")
}
```

> Sorry for late response, did not see this
